### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by re3Dprinting** [re3Dprinting/klipper_config#14]
Issue Reporter: Doug
Email: doug@re3d.org

Condition: Command sent

Details: Crammer keyboard disappears after every keystroke

Additional Observations: 

Log File:

**Comment by re3Dev** [comment]
New release V0.4.0 with updated system packages seems to have improved the chromium keyboard plugin and handling. Labeling as Complete for now unless issue repeats after upgrade.
