### ISSUE TITLE
Gigabot, Gigabot XLT, Terabot, Exabot, GigabotX, GigabotX XLT -  -- Motion

### ISSUE THREAD

**Issue by re3Dprinting** [re3Dprinting/klipper_config#20]
Gigabot, Gigabot XLT, Terabot, Exabot, GigabotX, GigabotX XLT -  -- Motion --- 5/2/2023 12:48:31

Mainsail Version: 2.3.0-beta1
Moonraker Version: 0.7.1-453-gee312ee
Klipper Version: 0.10.0-297-gdeeb1af3

Issue Condition: Macro

Issue Details: When using the disable ditto printing macro, extruder1 won't respond to commands.

Photos: 

Log Files:

**Comment by re3Dev** [comment]
See commit [#0963afe](https://github.com/re3Dprinting/klipper_config/commit/0963afe6f93de61961d008662ff911448622a958) for the fix.
