### ISSUE TITLE
Gigabot - Test -- Other

### ISSUE THREAD

**Issue by re3Dprinting** [re3Dprinting/klipper_config#22]
Gigabot - Test -- Other --- 5/10/2023 10:45:21

Mainsail Version: Test
Moonraker Version: Test
Klipper Version: Test

Issue Condition: Test

Issue Details: Test

Photos: 

Log Files:

**Comment by re3Dev** [comment]
Test Comment

**Comment by re3Dev** [comment]
Test comment 2
