### ISSUE TITLE
Gigabot XLT - 691 -- Motion

### ISSUE THREAD

**Issue by re3Dprinting** [re3Dprinting/klipper_config#23]
Gigabot XLT - 691 -- Motion --- 5/13/2023 10:41:02

Mainsail Version: 2.3.0-beta1
Moonraker Version: 0.7.1-453
Klipper Version: 0.10.0-297

Issue Condition: Printing

Issue Details: Change X/Y accel to 2000, decel to 1000, Z accel to 15-30

Photos: 

Log Files:

**Comment by re3Dev** [comment]
Request complete for FFF configurations. See [#efd3833](https://github.com/re3Dprinting/klipper_config/commit/efd383379f0d44de656ac2f033a8782d32e8f421) for changes.
