### ISSUE TITLE
GigabotX - UT -- Motion

### ISSUE THREAD

**Issue by re3Dprinting** [re3Dprinting/klipper_config#25]
GigabotX - UT -- Motion --- 5/17/2023 13:38:30

Mainsail Version: 2.3.0-beta1
Moonraker Version: 0.7.1-486-g9b5b3cc
Klipper Version: 0.10.0-297-gdeeb1af3

Issue Condition: Command Sent

Issue Details: After loading gcode and clicking "print", while the printer was heating up, I clicked pause build. Once paused, I hit stop build. The extruder moved all the way to the +Y direction. I was able to recreate this issue, which is what the klippy log should show.

Photos: 

Log Files: 
https://drive.google.com/open?id=1iEZgNkh2TVbZqRlxEoQKf3v0E20FSggr

**Comment by re3Dev** [comment]
Would you mind sending me the gcode file that was used to print? (either post here or email me)

**Comment by re3Dev** [comment]
This is normal operation for machine commands. GCODE commands are single threaded and run sequentially in a queue. So commands were put in the queue like so:  Start Print -> Pause -> Stop. The pause command is run before the stop command and 'parks' the print head in the positive Y position. We have two different pause commands: PAUSE & PAUSE_NO_PARK.
