### ISSUE TITLE
Gigabot, Gigabot XLT, Terabot, Exabot, GigabotX, GigabotX XLT - same -- Motion

### ISSUE THREAD

**Issue by re3Dprinting** [re3Dprinting/klipper_config#28]
Gigabot, Gigabot XLT, Terabot, Exabot, GigabotX, GigabotX XLT - same -- Motion --- 6/5/2023 15:08:10

Mainsail Version: same
Moonraker Version: same
Klipper Version: same

Issue Condition: Configuration

Issue Details: Please pass 1mm move increment as standard

Photos: 
https://drive.google.com/open?id=1x3rlanMPiIaR8U6Bi6pKUy7tON6L46nL

Log Files:

**Comment by re3Dev** [comment]
Implementing into future images. This is done through the GUI so no commit is made.
